### ISSUE TITLE
Question about future projects

### ISSUE THREAD

**Issue by HIKORIN01** [seth-js/yomichan-fr#2]

**Comment by HIKORIN01** [comment]
Are you planning on making more yomichan dictionaries, or will you be moving towards something else?

**Comment by seth-js** [comment]
Sorry for the late reply. I don't plan on making more dictionaries unless there's some demand and it seems possible.

Recently, I've been using [whisper](https://github.com/openai/whisper) to create matching subtitles for dubs, audiobooks, podcasts, and YouTube videos. The results have been super promising for Spanish.
