### ISSUE TITLE
Firefox error 

### ISSUE THREAD

**Issue by Luca312** [seth-js/yomichan-fr#4]
I have this problem when trying to load the add on

There was an error during the temporary add-on installation.

**Comment by seth-js** [comment]
Sorry for the super late reply.

I can't think of any reason you'd have an issue installing it, as it's worked on every setup I've tried it on. If you're still having issues, I recommend just using the latest version of [Yomitan](https://github.com/themoeway/yomitan/releases) (at least version 24.2.23.0), as it now supports non-Japanese languages including French.

You can get a much nicer and more up-to-date French dictionary compatible with Yomitan from another project I've worked on [here](https://github.com/themoeway/kaikki-to-yomitan/releases/tag/beta). You'll want to download and import `kty-fr-en-ipa.zip` and `kty-fr-en.zip`.
